# Generado por Noctalia (user-template hyprlock) — no editar a mano.
# Fondo: ~/.config/hypr/wallpaper.jpg lo mantiene el hook wallpaper_changed.

general {
    ignore_empty_input = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpaper.jpg
    color = rgba({{ colors.surface.default.hex_stripped }}ff)
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# RELOJ
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba({{ colors.on_surface.default.hex_stripped }}ff)
    font_size = 120
    font_family = Fira Semibold
    position = 0, -300
    halign = center
    valign = top
}

# USUARIO
label {
    monitor =
    text = Hola, $USER
    color = rgba({{ colors.on_surface_variant.default.hex_stripped }}ff)
    font_size = 25
    font_family = Fira Semibold
    position = 0, -40
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba({{ colors.primary.default.hex_stripped }}cc)
    inner_color = {{ colors.surface.default.rgba | set_alpha 0.5 }}
    font_color = {{ colors.on_surface.default.rgb }}
    fade_on_empty = false
    placeholder_text = <i>Contraseña...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}
